name: Deploy

on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy to environment'
        required: true
        type: environment
        default: 'Stage'

jobs:
  secrets-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check DEPLOY_SERVER
        run: |
          if [ -z "${{ secrets.DEPLOY_SERVER }}" ]; then
            echo "Error: DEPLOY_SERVER not set."
            exit 1
          fi

      - name: Check DEPLOY_USER
        run: |
          if [ -z "${{ secrets.DEPLOY_USER }}" ]; then
            echo "Error: DEPLOY_USER not set."
            exit 1
          fi

      - name: Check DEPLOY_PATH
        run: |
          if [ -z "${{ secrets.DEPLOY_PATH }}" ]; then
            echo "Error: DEPLOY_PATH not set."
            exit 1
          fi

      - name: Check SSH_PRIVATE_KEY
        run: |
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "Error: SSH_PRIVATE_KEY not set."
            exit 1
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: secrets-check
    environment: ${{ inputs.environment || 'Production' }}
    if: >-
      ${{ (github.event.workflow_run.conclusion == 'success') ||
          (github.event_name == 'workflow_dispatch') }}

    env:
      DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts

      - name: Deploy live
        run: |
          rsync -avz --delete \
            --exclude '.git' \
            --exclude '.github' \
            --exclude '.env' \
            --exclude 'tests' \
            --exclude 'settings.php' \
            --exclude 'config' \
            --exclude 'models/' \
            ./ $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH

      - name: Post-deploy tasks
        run: |
          ssh $DEPLOY_USER@$DEPLOY_SERVER << EOF
            echo "Deploying to $DEPLOY_PATH"
            cd $DEPLOY_PATH
            composer install --no-dev --optimize-autoloader
            ./vendor/bin/drush cr
            ./vendor/bin/drush updb -y
          EOF
