name: Deploy

on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    env:
      DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts

      - name: Deploy live
        run: |
          rsync -avz --delete \
            --exclude '.git' \
            --exclude '.github' \
            --exclude '.env' \
            --exclude 'tests' \
            --exclude 'settings.php' \
            --exclude 'config' \
            ./ $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH

      - name: Post-deploy tasks
        run: |
          ssh $DEPLOY_USER@$DEPLOY_SERVER << EOF
            echo "Deploying to $DEPLOY_PATH"
            cd $DEPLOY_PATH
            composer install --no-dev --optimize-autoloader
            ./vendor/bin/drush cr
            ./vendor/bin/drush updb -y
          EOF
